- README.md
- dbxml/foodprintDB_config.sql
- server.js
- views/contact.ejs
- views/scanresult.ejs
- views/scanresultv1.ejs
* Description: Sanitize req.params. Update scan templates. Add weekly view db table and logic. Update contact email address. Update readme with node terminal instructions for testing.
* Testing: Tested locally in dev env
> FoodPrint Updates

- views/scanresult.ejs
* Description: Update scan template.
* Testing: N/A
> Updaet template

- .gitignore
- README.md
- dbxml/FoodPrint_19082020.sql
- dbxml/FoodPrint_20082020.sql
- dbxml/FoodPrint_21082020.sql
- dbxml/foodprintDB_harveststorage.sql
- package-lock.json
- package.json
- routes/harvest.js
- routes/storage.js
- server.js
- src/css/tempusdominus-bootstrap-3.css
- src/js/tempusdominus-bootstrap-3.js
- views/harvestlogbook.ejs
- views/partials/head.ejs
- views/scanresult.ejs
- views/scanresultv1.ejs
- views/storagelogbook.ejs
**Description**
- Update gitignore
- Relocate error handling to end of server file
- Add Google Analytics
- Add image upload to Harvest Logbook
- Add logfile in DEV
- Harvest and Storage DB schema changes (Some VARCHARS to DATETIME fields, Photo from varchar to BLOB)
- Add new suppliers
- Add checkboxes for produce description - organic, conventional, free range etc
- Include save to Weekly View when saving Storage
**Testing**
- Successfully Tested in DEV
> Feature Updates

- src/js/foodprint_blockchain.js
- views/blockchain_explorer.ejs
**Description**
- Add current Eth Wallet address and latest deployed contract details (testnet contract address, tx, deployer address) to Blockchain Config section
**Testing**
- Successfully tested in DEV
> Blockchain Configuration in Blockchain Explorer

- server.js
- views/harvestlogbook.ejs
- views/storagelogbook.ejs
Add new produce types:
- EKLN_Limes
- EKLN_Granadilla
- QCGF_Parsley
- QCGF_PakChoi
- BGSM_Mor
- OZCF_Leeks
- OZCF_Radish
- OZCF_Herbs
> Add new produce types

- dbxml/FoodPrint_Production_10112020.sql
- package-lock.json
- views/index.ejs
Description: Added record for test QR code. Updated highlights/traction on home page.
> Updates from 10 November 2020

- dbxml/FoodPrint_Production_10112020.sql
- package-lock.json
- package.json
- views/about.ejs
- views/checkin.ejs
- views/contact.ejs
- views/index.ejs
- views/partials/footer.ejs
- views/partials/head.ejs
Description: Updated project deps. Updated UI copy e.g. Fresh food, from farm-to-fork (instead of tracing the worlds food)
> Deps and UI Copy updates

- package-lock.json
- package.json
Description: Deployment requires specific versions of Node and NPM. These have been updated otherwise ` Dangerous semver range (>) in engines.node` error happens
> Update Node deps 

- views/about.ejs
- views/index.ejs
Description: Update home and about web copy
> Update home and about web copy

- views/index.ejs
> Update home copy

- views/index.ejs
* Description - minor home page update
> Update home web copy 

- views/index.ejs
*Description: Add Foodprint wholesale
*Testing: Tested locally
> Add Foodprint wholesale

- views/contact.ejs
- views/partials/footer.ejs
* Description - Updating company name and socials.
* Testing - Low risk, quick push.
> Update socials and company name

- dbxml/FoodPrintSchemaDump20210814.sql
- docker-compose.yaml
- package-lock.json
- routes/auth.js
- routes/harvest.js
- routes/storage.js
**Exposed relevant  API endpoints required to support WhatsApp Chatbot as follow**
- Added a user model via SQL migrations, and exposed registration endpoint, and registration status endpoint.
- Created a method which exposes harvest creation via API with minimal fields
- Created a method which exposes storage creation via API with minimal fields
**WhatsApp registration endpoint**
**WhatsApp check registration status**
**WhatsApp create harvest minimal fields**
**WhatsApp create storage  minimal fields**
**Additional Stuff**
- Added user table SQL migration
- Added a docker-compose file for spinning up a local db during development
> added relevant whatsapp end points

- routes/auth.js
Improved the WhatsApp registration endpoint to return user info on success. This is necessary as it reduces round trips that are made by the WhatsApp chatbot.
> improved whatsapp registration endpoint

- dbxml/FoodPrintSchemaDump20210814.sql
- docker-compose.yaml
- package-lock.json
- package.json
- routes/auth.js
- routes/harvest.js
- routes/storage.js
- views/partials/header.ejs
* Description 
- Social media links updated in footer and burger menu
- WIP WhatsApp chatbot endpoints.
> Social Media Handle updates and WhatsApp EndPoints

- views/partials/footer.ejs
* Description - Add SA reg in footer for Facebook Chatbot
* Testing - N/A
> Add SA reg in footer for Facebook Chatbot

- README.md
- dbxml/FoodPrint_20211119.sql
- models/foodprint_config.js
- models/foodprint_harvest.js
- models/foodprint_qrcount.js
- models/foodprint_storage.js
- models/foodprint_subscription.js
- models/foodprint_weeklyview.js
- models/init-models.js
- models/market_subscription.js
- models/user.js
- package.json
- routes/auth.js
- routes/config.js
- routes/harvest.js
- routes/storage.js
- server.js
- src/js/db_sequelise.js
- src/js/sequelise_auto_export.js
- views/storagelogbook.ejs
- views/test_db.ejs
- generated models with sequelize auto FoodprintHarvest, FoodprintStorage, FoodprintQrcount, FoodprintWeeklyview, FoodprintConfig, User, MarketSubscription and FoodprintSubscription which are in `models` folder
- updated the logic in `server.js` , `routes/storage.js` and `routes/harvest.js` to use sequelize and the generated models
- /app/scan/:id
- /app/api/v1/scan/:id
- /subscribe
- /app/traceproduce
- /checkin/:market_id
- /register/whatsapp
- /register/status/:phoneNumber
- /marketcheckin
- all routes in routes/storage.js
- all routes in routes/harvest.js
- all routes in routes/config.js
- added a migration script `FoodPrint_20211119.sql` to change data type for harvest_TimeStamp and harvest_CaptureTime on table foodprint_weeklyview from string to date
- added necessary configs to …
> Sequelize models and route logic update

- package-lock.json
*Description: Follow up to https://github.com/FoodPrintLabs/foodprint/pull/69 after commit after npm install and npm audit fix
> Code cleanup v3 continued

- package-lock.json
- package.json
* Description: install axios package as not available by default on production server
* Testing: app starts in dev.
> Add axios package

- README.md
- package.json
- routes/api_v1.js
- routes/harvest.js
- routes/qrcode.js
* Description:
- Update binary to base64 encoding from depracated  `new Buffer()` to more secure and usable `Buffer.from()`
- Update Heroku commands in readme
- Automate sequelize migration
* Testing:
- Tested quickly in Dev and adding/viewing harvest worked.
> Technical debt fixes and enhancements

- tests/sequelize.js
* description - starting point for sequelize tests
* testing - successfully ran node ./tests/sequelize.js
> Sequelize tests starter

- routes/api_v1.js
- routes/harvest.js
- routes/qrcode.js
- routes/storage.js
* Description: Follow up to https://github.com/FoodPrintLabs/foodprint/pull/72 - there are cases when rows[i].harvest_photoHash is null and Buffer.from() would throw TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null.
Also added more logging in order to see this in the console in future.
* Testing - Quickly tested in Dev
> Fix Buffer.from() bug  and add more logging

- routes/api_v1.js
- routes/harvest.js
- routes/qrcode.js
- routes/storage.js
- tests/sequelize.js
* Description: Port of https://github.com/FoodPrintLabs/foodprint/pull/76
> Port of Fix Buffer.from() bug and add more logging

- routes/dashboards.js
- views/dashboard_admin.ejs
- views/dashboard_farmer.ejs
- Added Super user access,
- Updated default filter and error message (1 month/ Incorrect filter received)
- Finished active filter buttons
> Dash Dev Changes

- package.json
- routes/qrcode.js
Completed F2F routing issue allowing data to be rendered
> Completed: Farm to form fix

- package.json
- routes/qrcode.js
- src/css/timeline.css
- tests/test_supplier_produce_scan.js
- views/scanresult.ejs
Look through documentation for resolution fix OR use data and create custom timeline
> Provenance CSS Resolution fix and TEST_Beetroot Script

- models/init-models.js
- models/my_orders.js
- routes/order.js
- server.js
- views/order_dashboard.ejs
- views/partials/header.ejs
FOODPRINT WHOLESALE - FOODPRINT-104
ORDER DASHBOARD
> Order dash dev

- package.json
- tests/produce.js
Port of https://github.com/FoodPrintLabs/foodprint/pull/110
> Remove current folder reference in node scripts

- .prettierignore
- .sequelizerc
- README.md
- config/db/db_sequelise.js
- config/db/dbconfig.js
- config/email/email.js
- package.json
* Description - still running into sequelize migration issues on Heroku and hopefully this resolves it. Added sequelize config file `.sequelizerc` and updated config file to use env variables
related to https://github.com/FoodPrintLabs/foodprint/pull/110
> Sequelize / Db config updates

- routes/produce.js
- routes/test.js
- views/index.ejs
- views/partials/header.ejs
- views/test_config.ejs
* Description - Add PDF route for Whatsapp i.e. with no auth `/pricepage/pdf/whatsapp`
> Add PDF route for whatsapp

- config/email/orderEmailTemplate.js
- routes/email.js
- server.js
- views/email.ejs
- views/order_dashboard.ejs
Email Logs Template allows admin to view emails
> Email model UI

- config/db/db_sequelise.js
- config/db/dbconfig.js
- config/email/email.js
- utils/enums.js
* Desc - Time to move to Postgres and say goodbye to MySQL. This change still works for MySQL though. The env variables of interest are DATABASE_URL and DB_DIALECT
* Testing - Further testing required :(
Testing on Postgres (NB port normally 5432)
DATABASE_URL=postgres://username:pwd@host:port/dbname 
DB_DIALECT=postgres
Testing on MySQL
DATABASE_URL=mysql://username:pwd@host/db
DB_DIALECT=mysql
> Postgres migration

- package.json
> rather run db migrations manually for now

- views/index.ejs
- views/partials/header.ejs
* Description - update home page links - added Demo QR Code and Email Logs to Configuration Card
> Update home links

- routes/produce.js
- views/harvestlogbook.ejs
- views/storagelogbook.ejs
Description 
- Make Produce PDF available to any logged in user.
- Add FoodPrint TEST as supplier.
Testing - tested in DEV
> UI and Permission Updates

- models/foodprint_qrcode.js
- models/foodprint_qrcode_product_attributes.js
- routes/qrcode.js
- src/css/custom.css
- views/dashboard_qrcode.ejs
- views/dashboard_qrcode_attributes.ejs
- views/qrcode_product.ejs
> QRCode generation and Product attribute timeline

- config/digitalocean/file-upload.js
- routes/produce.js
- tests/test_digitaloceanfileexists.js
Create a service file in config folder for Digital Ocean file uploads
> Digitalocean service

- config/digitalocean/file-upload.js
- migrations/20220801134730-qrcode_column_updates.js
- models/foodprint_qrcode.js
- models/foodprint_qrcode_product_attributes.js
- package.json
- routes/produce.js
- routes/qrcode.js
- views/dashboard_qrcode.ejs
- views/harvestlogbook.ejs
- views/qrcode_product.ejs
> Digitalocean logo upload + PR139 Updates

- migrations/20220812092902-add-columns-qrcount.js
- models/foodprint_qrcount.js
- routes/qrcode.js
- views/dashboard_qrcode_scans.ejs
> QR Code analytics Dashboard and Static Scan tracking

- views/buyerlogbook.ejs
- views/myorderlogbook.ejs
- views/produce.ejs
- views/produce_price.ejs
- views/sellerlogbook.ejs
- views/storagelogbook.ejs
Updated Storage handover logbook UI for both Action Buttons and dropdowns. Also updated other logbooks icons
> Logbook UI updates 

- server.js
- views/index.ejs
When a user Logs in the Configuration Card should only be accessible if the user is an Admin or SuperUser
**Home Page for non-Admin**
**Home Page for Admin**
> Configuration card restricted to admin/superuser

- src/css/custom.css
- views/order_dashboard.ejs
Updated the Order Dashboard UI readability
> Order Dashboard UI updates

- migrations/20220825122057-add-column-storage-qrcode-url.js
- models/foodprint_storage.js
- routes/qrcode.js
- routes/storage.js
- src/css/custom.css
- views/dashboard_qrcode_attributes.ejs
- views/dashboard_qrcode_static.ejs
- views/dashboard_qrcode_supplier.ejs
- views/index.ejs
- views/partials/header.ejs
- views/storagelogbook.ejs
> Storage Supplier Produce QR Code

- routes/storage.js
A fix for past handovers not allowing logbook to load when generating qrcodes with no qrcode url. Fix-recreate qrcodes with available data
> Storage QR code update

- views/harvestlogbook.ejs
- views/storagelogbook.ejs
**Initial List**
**When choosing a code the farm name is automated**
**The produce list is also populated**
**Once the produce is chosen the supplier produce shortcode is automatically chosen**
**Successfully added after filling in the rest of the form**
>  Dynamic dropdown lists on add harvest modal

- views/buyerlogbook.ejs
- views/dashboard_admin.ejs
- views/dashboard_farmer.ejs
- views/order_dashboard.ejs
- views/produce_price.ejs
- views/sellerlogbook.ejs
The filtercheck() function was too long. The use of an **array, loop and check** shortened the code significantly. Also allows for easy scalability by adding a new filter value to the array and applying it to the dropdown to choose from. For our more advanced activatefilter() you need to add the new filter type to that array as well as the original filtercheck() array then you also add the changes for it in the route.
> FilterCheck() Simplify Update

- views/harvestlogbook.ejs
- views/storagelogbook.ejs
> Temp fix for auto dropdowns on harvest and storage for view, edit and delete

- views/harvestlogbook.ejs
- views/storagelogbook.ejs
Port of https://github.com/FoodPrintLabs/foodprint/pull/162
> Port of Temp fix for auto dropdowns on harvest and storage for view, edit and delete

- routes/api_v1.js
**Bids request result in postman**
**Offers request result in postman**
> Created Bid and Offers API Request to get all "Placed" Offers

- views/index.ejs
- views/partials/notificationbar.ejs
> Dev home UI update

- routes/api_v1.js
> Swagger for produce price

- routes/qrcode.js
> Supplier QR Codes

- src/css/custom.css
- views/blockchain_explorer.ejs
- views/buyerlogbook.ejs
- views/dashboard_admin.ejs
- views/dashboard_farmer.ejs
- views/dashboard_qrcode_static.ejs
- views/dashboard_qrcode_supplier.ejs
- views/email.ejs
- views/harvestlogbook.ejs
- views/index.ejs
- views/myorderlogbook.ejs
- views/order_dashboard.ejs
- views/produce.ejs
- views/produce_price.ejs
- views/sellerlogbook.ejs
- views/storagelogbook.ejs
- views/trace_produce.ejs
I have made updates to the burger menu and I have updated the harvest-log page.
> Burger Menu Update, and Other Pages Update

- src/css/custom.css
- views/buyerlogbook.ejs
- views/dashboard_qrcode_attributes.ejs
- views/dashboard_qrcode_static.ejs
- views/dashboard_qrcode_supplier.ejs
- views/produce.ejs
- views/produce_price.ejs
- views/sellerlogbook.ejs
Home Screen
QR Configuration Static
QR Configuration Supplier
Working On This:
I am going to write a script to test the UI, with different inputs and data. I just realized that the UI might have problems when the input data scales. Then I will fix the UI issues.
> Home Page And Other Pages Edits

- views/buyerlogbook.ejs
- views/order_dashboard.ejs
- views/partials/head.ejs
- views/sellerlogbook.ejs
Marketplace updates:
- Rename bid to buy offer
- Rename offer to sell offer
Update head title to "Connecting farmers to markets & financial services"
Successfully tested in dev.
> Buy Offer (Bid), Sell Offer (Offer) and Head Title Update

- migrations/20230119214614-harvest_channel_twilio_url.js
Forgot to include this in https://github.com/FoodPrintLabs/foodprint/pull/177
> add seqeulize migration for harvest table - twilio url and log channel

- routes/harvest.js
* Description: timeout when saving images from WhatsApp -> Twilio -> Digital Ocean
> add logging to save whatsapp harvest
